
name: 'Build and Publish'

on:
 pull_request:
   types:
     - closed
  
jobs:
  deployToDevelop:
    if: github.event.pull_request.merged == true
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "deployed"