name: Build and deploy user service to qa environment

env:
  VAR_TAG_NAME: 'QA_TAG'
  REPO_NAME: $(basename ${{ github.repository }})
  URL_OPTIONS: '-H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{secrets.VAR_READ_WRITE_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/variables'
on: 
  # push:
  #   tags:
  #     - 'qa-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Enter the quality tag'
        # Default value if no value is explicitly provided
        default: 'qa-0.0.1'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        # type: string

jobs:
  BuildAndPushImageToECR:
    name: Build qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: build and tag
        run: echo "deployed ${{ github.event.inputs.tag }}"
      - name: crate image tag repo variable
        if: $(curl -L -s  ${{ env.URL_OPTIONS }}/${{ env.VAR_TAG_NAME }} | jq -r .message) == ''
        run: curl -L -s  -X POST ${{ env.URL_OPTIONS }} -d '{"name":"${{ env.VAR_TAG_NAME }}","value":"${{ github.event.inputs.tag }}"}'
      - name: update image tag repo variable
        if: $(curl -L -s  ${{ env.URL_OPTIONS }}/${{ env.VAR_TAG_NAME }} | jq -r .message) == 'Already exists - Variable already exists'
        run: curl -s -L -X PATCH  ${{ env.URL_OPTIONS }}/${{ env.VAR_TAG_NAME }} -d '{"name":"${{ env.VAR_TAG_NAME }}","value":"${{ github.event.inputs.tag }}"}'
      - name: repo name
        run: echo ${{ github.event.repository.name }}
        # run: echo "Repo - $(basename ${{ github.repository }})"