name: Build and deploy user service to qa environment

on:
  push:
    tags:
      - 'qa-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Enter the quality tag'
        # Default value if no value is explicitly provided
        default: 'qa-<version>'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  BuildAndPushImageToECR:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          run: echo "deploy ${{ inputs.Tag }}"
