name: Build and deploy user service to qa environment

env:
  URL_OPTIONS: '-H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{secrets.VAR_READ_WRITE_TOKEN}}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/variables'
on:
  # push:
  #   tags:
  #     - 'qa-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Enter the quality tag'
        # Default value if no value is explicitly provided
        default: 'qa-<version>'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        # type: string

jobs:
  BuildAndPushImageToECR:
    name: Build qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: build and tag
        run: echo "deployed ${{ github.event.inputs.tag }}"
      - name: update image tag repo variable
        run: >
          STATUS=$(curl -L -s  ${{ env.URL_OPTIONS }}/QA_TAG | jq -r .message)

          create_tag_var() {
            curl -L -s  -X POST ${{ env.URL_OPTIONS }} -d '{"name":"QA_TAG","value":"${{ github.event.inputs.tag }}"}'
          }

          update_tag_var() {
            curl -s -L -X PATCH  ${{ env.URL_OPTIONS }}/QA_TAG -d '{"name":"QA_TAG","value":"${{ github.event.inputs.tag }}"}' 
          }

          if [[ $STATUS == "Already exists - Variable already exists" ]];then update_tag_var; else create_tag_var; fi